// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0WqDfvkHWcO-gONs0jmtuTxySjOu07Qc',
    appId: '1:610563416958:web:68e0cd3f32648f500b092f',
    messagingSenderId: '610563416958',
    projectId: 'projet1-f451b',
    authDomain: 'projet1-f451b.firebaseapp.com',
    storageBucket: 'projet1-f451b.firebasestorage.app',
    measurementId: 'G-Y85G2WWKBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsouAQByc6u339LBGkZj05OUnraHma8Jg',
    appId: '1:610563416958:android:2eccc8dfd715681e0b092f',
    messagingSenderId: '610563416958',
    projectId: 'projet1-f451b',
    storageBucket: 'projet1-f451b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPTbvR6FTIcpBCs78a1h6-v1ThnByFrgY',
    appId: '1:610563416958:ios:6b630bc1eb5d313f0b092f',
    messagingSenderId: '610563416958',
    projectId: 'projet1-f451b',
    storageBucket: 'projet1-f451b.firebasestorage.app',
    iosBundleId: 'com.example.projet1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPTbvR6FTIcpBCs78a1h6-v1ThnByFrgY',
    appId: '1:610563416958:ios:6b630bc1eb5d313f0b092f',
    messagingSenderId: '610563416958',
    projectId: 'projet1-f451b',
    storageBucket: 'projet1-f451b.firebasestorage.app',
    iosBundleId: 'com.example.projet1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0WqDfvkHWcO-gONs0jmtuTxySjOu07Qc',
    appId: '1:610563416958:web:504e1e3b70a1dd0e0b092f',
    messagingSenderId: '610563416958',
    projectId: 'projet1-f451b',
    authDomain: 'projet1-f451b.firebaseapp.com',
    storageBucket: 'projet1-f451b.firebasestorage.app',
    measurementId: 'G-XDCXMYJEGE',
  );
}
